### ISSUE TITLE
Provide configuration file for udev to give permissions on devices

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ColinPitrat/kalenji-gps-watch-reader#29]
```
This would be nice to include udev configuration file in the repository to ease 
installation and usage.
```

Original issue reported on code.google.com by `colin.pi...@gmail.com` on 7 Jun 2014 at 3:05

**Comment by ColinPitrat** [comment]
An example provided by a Debian user:
https://code.google.com/p/kalenji-gps-watch-reader/issues/detail?id=48

# Keymaze 500 Hike
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", MODE:="0666"

**Comment by ColinPitrat** [comment]
Provided in etc/10-kalenji-udev.rules
Up to the user or the packaging to place it at the right place
