### ISSUE TITLE
link to similar project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ColinPitrat/kalenji-gps-watch-reader#42]
```
I started a similar project for a different, commonly rebranded GPS watch. I 
propose to add links to each other's project. 


https://github.com/mru00/crane_gps_watch

Best Regards, 
Rudolf
```

Original issue reported on code.google.com by `rudolf.m...@gmail.com` on 19 Nov 2014 at 9:29

**Comment by ColinPitrat** [comment]
Added a link in the readme of the project.
Would be nice however if we managed to join our efforts so that users of all watch types can benefit of all features of both projects.
