### ISSUE TITLE
incomplete summary of data when reading Onmove710

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ColinPitrat/kalenji-gps-watch-reader#47]
```
What steps will reproduce the problem?
Reading data from Onmove 710.

What is the expected output? What do you see instead?
Expected data is: session number - session date - session time - number of laps 
- total distance - total time
But I always get: session number - session date - session time - 999 laps - 0 
km - 0s

What version of the product are you using? On what operating system?
My device is an onmove710, and i run your program using windows 7.

Please provide any additional information below.
It's a great tool that works fine. This is not a big issue, because I can 
identify the sessions by date and time. So if it's to much work, don't bother.

```

Original issue reported on code.google.com by `eindhove...@gmail.com` on 11 Mar 2015 at 7:15

**Comment by ColinPitrat** [comment]
Hello,

this issue has been fixed.
This was a "TODO" in the original implementation.

Please confirm this works well with git tip, or reopen in case this doesn't work.

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello Colin,

Is this issue also fixed in the Windows-version? I went to the downloadsection en downloaded the latest version, which is Windows version 4.9.2 (release date nov 8, 2014). No luck: data summary is still incomplete.

**Comment by ColinPitrat** [comment]
Hello,

I didn't release it, mainly because I didn't know how to handle it properly on GitHub. This is now done.
You can download release 4.9.3:
https://github.com/ColinPitrat/kalenji-gps-watch-reader/releases/tag/v4.9.3

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello Colin,

You're the best! Version 4.9.3 is working correctly. I can confirm that this issue is solved using Geonaute ONmove710 on Windows 7.

Regards,
Nicolas
