### ISSUE TITLE
Site web pour conversion en GPX 

### ISSUE THREAD

**Issue by DOCPROF** [ColinPitrat/kalenji-gps-watch-reader#58]
Juste une proposition : 
Pourquoi pas créer un site web de conversion des fichier de le série OnMove (et autre) en format standard (GPX).
Jean.

**Comment by ColinPitrat** [comment]
Plusieurs raisons pour lesquelles je ne le ferai pas:
 - c'est beaucoup de travail pour quelques montres seulement (celles qui utilisent des fichiers). Il n'y a pas que le développement, il faut mettre en place et maintenir le site web
 - si le site est inaccessible, les utilisateurs sont bloqués. En général si le programme marche à un moment, sans action de l'utilisateur il continuera à marcher la fois suivante. Et si il ne marche plus l'utilisateur pourra généralement régler le problème lui même.
 - il est possible de configurer le programme et le système pour réduire au maximum les actions à executer. Ainsi, simplement brancher la montre peut executer kalenji_reader avec la configuration par défaut et importer tous les fichiers.
 - sans accès internet, il est quand même possible d'utiliser le programme pour importer les sessions (sans correction de l'altitude par GoogleMaps certes)

En fait le seul avantage que je vois à créer un site web, c'est que je pourrais y mettre de la pub et engranger des revenus :-)

Si quelqu'un veut développer un site web, je serai ravi de mettre un lien en page d'accueil comme alternative à l'installation de kalenji_reader. Si il propose les sources dans une pull-request propre je serai ravi de les intégrer dans le repository (c'est vrai aussi pour une GUI d'ailleurs) ce qui permettrait à n'importe qui d'héberger sa propre instance.

Mais je ne prévois pas (pour l'instant en tout cas) de le faire moi même.
