### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by grodin** [ColinPitrat/kalenji-gps-watch-reader#61]
It would be useful to document in the README what dependencies are needed to build this. It's not too hard to find out what you need to install to build it, but it would be good to explicity list them in the README.

**Comment by ColinPitrat** [comment]
Good idea. You can send a PR if you want. Otherwise I'll do it in the coming days.

**Comment by ColinPitrat** [comment]
Added in b6d62b03a8e38a27cbd20844102112478e960b09
