### ISSUE TITLE
OneMove200 ne se monte plus

### ISSUE THREAD

**Issue by FredCoadou** [ColinPitrat/kalenji-gps-watch-reader#76]
Bonjour, ma montre OneMove200 ne se monte plus sur mes ordinateurs.
J'ai un ordinateur qui tourne sous Ubuntu et un autre sous Debian.
Je branche la montre mais elle n'aparait pas dans mon gestionnaire de dossier, comme auparavant et donc lorsque je lance votre script il ne fonctionne pas...
Si vous pouviez m'aider...
Merci

**Comment by ColinPitrat** [comment]
C'est de l'USB Mass Storage. Une clef USB fonctionne-t-elle bien ? Si oui, la montre est probablement endommagée. Tester quand même sur un autre ordinateur pour vérifier.

**Comment by FredCoadou** [comment]
C'est bien ce que je craignais... Ca fait ça sur deux ordinateurs différents avec OS différents... Je vais essayer de transférer mes données via bluethooth sur mon smartphone... Merci !
