### ISSUE TITLE
support heart rate onMove220

### ISSUE THREAD

**Issue by zaurelzo** [ColinPitrat/kalenji-gps-watch-reader#82]
Hi Colin,
Is there on option in order to include the heart rate information into the generated gpx files ? I owned the onMove220 watch, and I am sure that my watch support a heart rate device since I have tested it and it gives me the average heart rate at the end of an activity.
Thanks.

**Comment by ColinPitrat** [comment]
Yes: https://github.com/ColinPitrat/kalenji-gps-watch-reader/wiki/Configuration-File#gpx-output-options

**Comment by zaurelzo** [comment]
It works perfectly. Thank Colin.
